# Generated by Django 3.2.6 on 2021-09-07 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration_login_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserManager',
        ),
    ]
